---
# Monitoring and Health Check Role
- name: Create monitoring scripts directory
  ansible.windows.win_file:
    path: "C:\\Scripts\\Monitoring"
    state: directory

- name: Create reports directory
  ansible.windows.win_file:
    path: "C:\\Scripts\\Reports"
    state: directory

- name: Deploy health check script
  ansible.windows.win_copy:
    src: "AD-HealthCheck.ps1"
    dest: "C:\\Scripts\\Monitoring\\AD-HealthCheck.ps1"

- name: Deploy performance monitoring script
  ansible.windows.win_copy:
    src: "Performance-Monitor.ps1"
    dest: "C:\\Scripts\\Monitoring\\Performance-Monitor.ps1"

- name: Create scheduled task for health monitoring
  community.windows.win_scheduled_task:
    name: "AD Health Check"
    description: "Daily Active Directory health check"
    actions:
      - path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        arguments: "-ExecutionPolicy Bypass -File C:\\Scripts\\Monitoring\\AD-HealthCheck.ps1"
    triggers:
      - type: daily
        start_boundary: "2023-01-01T06:00:00"
    username: "SYSTEM"
    state: present
    enabled: true

- name: Create scheduled task for performance monitoring
  community.windows.win_scheduled_task:
    name: "AD Performance Monitor"
    description: "Collect AD performance metrics every 15 minutes"
    actions:
      - path: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe"
        arguments: "-ExecutionPolicy Bypass -File C:\\Scripts\\Monitoring\\Performance-Monitor.ps1"
    triggers:
      - type: time
        repetition:
          interval: "PT15M"
        start_boundary: "2023-01-01T00:00:00"
    username: "SYSTEM"
    state: present
    enabled: true

- name: Run initial health check
  ansible.windows.win_powershell:
    script: |
      & "C:\\Scripts\\Monitoring\\AD-HealthCheck.ps1"
  register: initial_health_check
  failed_when: false

- name: Display health check results
  ansible.builtin.debug:
    var: initial_health_check.stdout_lines
  when: initial_health_check.stdout_lines is defined
