---
# DNS Server Configuration Role

- name: Deploy DNS configuration script
  ansible.windows.win_copy:
    src: "Configure-DNS.ps1"
    dest: "C:\\Scripts\\Configure-DNS.ps1"

- name: Configure DNS settings
  ansible.windows.win_powershell:
    script: |
      $params = @{
          DnsForwarders = @("{{ dns_forwarders | join('","') }}")
          DomainName = "{{ domain_name }}"
          DcIpPrefix = "{{ dc_ip_prefix }}"
      }
      & "C:\Scripts\Configure-DNS.ps1" @params
  register: dns_config_result
  when: is_primary_dc | default(false)

- name: Display DNS configuration results
  ansible.builtin.debug:
    var: dns_config_result.stdout_lines
  when:
    - is_primary_dc | default(false)
    - dns_config_result.stdout_lines is defined
