# Ansible Group Variables
# Main configuration for Windows Server 2025 AD deployment

# Template Compatibility Notes:
# - Template uses UEFI boot (ovmf) with TPM 2.0 and EFI disk
# - Primary disk is virtio0 (32GB) not scsi0
# - CPU type: x86-64-v2-AES, Machine: pc-q35-9.2+pve1
# - Requires cloud-init to be installed in template for network configuration
# - Boot order: virtio0 (not net0 as in template - will be changed after clone)

# Proxmox Configuration
proxmox_api_url: "https://172.16.30.10:8006/api2/json"
proxmox_user: "ansible@pve!automation"  # Note the !token-id format
proxmox_password: "{{ vault_proxmox_token }}"
proxmox_node: "Adamant"
proxmox_tls_insecure: true

# Windows Template Configuration
windows_template_name: "windows-server-2025-template"
windows_template_vm_id: 9000

# Domain Controller Configuration
dc_count: 2
dc_name_prefix: "dc"
dc_vmid_start: 200

# VM Resources - Template Inheritance vs Override
# When cloning from template, you can either:
# 1. INHERIT: Let cloned VMs use template's resource configuration (recommended)
# 2. OVERRIDE: Specify custom resources below (useful for standardization)

# Current approach: OVERRIDE template resources with standardized values
# This ensures consistent sizing regardless of template configuration
#dc_cpu_cores: 4
#dc_cpu_sockets: 1
#dc_memory_mb: 8192
#dc_cpu_type: "x86-64-v2-AES"  # Match template CPU type
#dc_machine_type: "pc-q35-9.2+pve1"  # Match template machine type
#dc_bios_type: "ovmf"  # UEFI boot for Windows Server 2025

# Alternative approach: INHERIT template resources
# To use template's CPU/memory settings, comment out the above variables
# and the playbook will clone with template's original configuration

# Storage Configuration
storage_pool: "pve-nvme"
# Template uses virtio0 (32GB) - disk sizes are inherited from template when cloning
# Only uncomment and specify if you need to:
# - Resize existing disks after clone (requires additional tasks)
# - Add additional disks beyond what's in the template
# os_disk_size: "80G"  # Only needed if resizing virtio0 after clone
# data_disk_size: "40G"  # Only needed if adding additional disks

# Network Configuration
network_bridge: "vmbr0"
dc_ip_prefix: "172.16.30"
dc_ip_start: 40
network_cidr_bits: 24
gateway_ip: "172.16.30.1"
dns_servers: "1.1.1.1 8.8.8.8"

# Active Directory Configuration
domain_name: "testdomain.local"
netbios_name: "TESTDOMAIN"

# Credentials (should be in vault)
admin_username: "Administrator"
# admin_password: stored as vault_admin_password
# dsrm_password: stored as vault_dsrm_password

# SSH Configuration  
ssh_public_key: "{{ vault_ssh_public_key }}"

# DNS Configuration
dns_forwarders:
  - "8.8.8.8"
  - "1.1.1.1"

# Organizational Units
organizational_units:
  - "Servers"
  - "Workstations" 
  - "Users"
  - "Groups"
  - "Service Accounts"

# AD Configuration
forest_functional_level: "WinThreshold"
domain_functional_level: "WinThreshold"
enable_recycle_bin: true
enable_backup: true
enable_monitoring: true

# Password Policy
password_policy:
  min_length: 14
  complexity_enabled: true
  max_password_age_days: 60
  min_password_age_days: 1
  password_history_count: 24
  lockout_threshold: 5
  lockout_duration_minutes: 30
  lockout_observation_window_minutes: 30
