---
# Main playbook for Windows AD deployment
- name: Deploy Windows Active Directory Domain Controllers
  hosts: domain_controllers
  gather_facts: yes
  become: no
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_shell_executable: None

  pre_tasks:
    - name: Wait for SSH connectivity
      ansible.builtin.wait_for_connection:
        timeout: 300

    - name: Gather Windows facts
      ansible.builtin.setup:

  roles:
    - windows_base
    - active_directory
    - dns_server
    - monitoring

  post_tasks:
    - name: Verify AD installation
      ansible.windows.win_service:
        name: NTDS
      register: ntds_service

    - name: Display deployment summary
      debug:
        msg: |
          Domain Controller {{ inventory_hostname }} deployment complete:
          - NTDS Service: {{ ntds_service.state }}
          - Domain: {{ domain_name }}
          - Role: {{ 'Primary DC' if is_primary_dc else 'Additional DC' }}
